import test from 'node:test'
import assert from 'node:assert/strict'
import { matchSnippet, mergeSearchSources, normalizeCandidate, parseCandidate, windowsToWsl } from '../src/core.js'
import { csvRows } from '../src/host.js'
import { configuredPreviewChannel, filterCachedSearchItems, parseCachedSearchQuery, pathInsideRoot, previewCapabilitiesOf, previewFamilyOf, previewMenuKind, sidebarRouteEligibility } from '../src/client-core.js'
import { renderDocument } from '../src/render.js'

test('converts Windows paths to WSL paths',()=>assert.equal(windowsToWsl('D:\\Files\\a.pdf'),'/mnt/d/Files/a.pdf'))
test('honors custom WSL drive mounts',()=>assert.equal(windowsToWsl('X:\\Files\\a.pdf',{X:'/mnt/q'}),'/mnt/q/Files/a.pdf'))
test('resolves workspace relative paths',()=>assert.equal(normalizeCandidate('docs/a.md','/work','/home/u'),'/work/docs/a.md'))
test('parses quoted Everything CSV',()=>assert.deepEqual(csvRows('\ufeffFilename,Size\r\n"D:\\a,b.txt",12\r\n'),[['Filename','Size'],['D:\\a,b.txt','12']]))
test('parses line ranges without confusing a Windows drive',()=>assert.deepEqual(parseCandidate('D:\\work\\app.ts:10-30'),{path:'D:\\work\\app.ts',lineStart:10,lineEnd:30}))
test('parses PDF pages and media time fragments',()=>{assert.deepEqual(parseCandidate('/docs/a.pdf#page=3'),{path:'/docs/a.pdf',page:3});assert.deepEqual(parseCandidate('/media/a.mp4#t=12.5'),{path:'/media/a.mp4',time:12.5})})
test('extracts the visible filename fragment beginning at the matched term',()=>{assert.equal(matchSnippet('儿童动画片合集 2026.mkv','动画片'),'动画片合集');assert.equal(matchSnippet('report-final.pdf','missing'),'路径')})
test('classifies preview families',()=>{assert.equal(previewFamilyOf({extension:'DOCX'}),'office');assert.equal(previewFamilyOf({extension:'mp4'}),'media');assert.equal(previewFamilyOf({extension:'wat'}),'other')})
test('checks workspace path boundaries without prefix collisions',()=>{assert.equal(pathInsideRoot('/work/a.txt','/work'),true);assert.equal(pathInsideRoot('/workspace/a.txt','/work'),false);assert.equal(pathInsideRoot('D:\\Work\\a.txt','D:\\Work'),true)})
test('selects PeekFile globally or a per-family channel',()=>{assert.equal(configuredPreviewChannel({previewRoutingMode:'peekfile-first'},{extension:'pdf'}),'peekfile');assert.equal(configuredPreviewChannel({previewRoutingMode:'sidebar-first'},{extension:'pdf'}),'peekfile');assert.equal(configuredPreviewChannel({previewRoutingMode:'custom',previewFamilyRoutes:{pdf:'peekfile'}},{extension:'pdf'}),'peekfile');assert.equal(configuredPreviewChannel({previewRoutingMode:'custom',previewFamilyRoutes:{pdf:'sidebar'}},{extension:'pdf'}),'sidebar')})
test('requires a custom Sidebar route, workspace containment, and a matching viewer',()=>{const base={preferences:{previewRoutingMode:'custom',previewFamilyRoutes:{pdf:'sidebar'}},target:{path:'/work/a.pdf',extension:'pdf'},cwd:'/work',sidebarAvailable:true,viewerMatched:true};assert.deepEqual(sidebarRouteEligibility(base),{eligible:true,reason:'sidebar'});assert.equal(sidebarRouteEligibility({...base,cwd:'/other'}).reason,'outside-workspace');assert.equal(sidebarRouteEligibility({...base,viewerMatched:false}).reason,'viewer-unavailable')})
test('declares only operations supported by each PeekFile viewer',()=>{const text=previewCapabilitiesOf({extension:'ts'}),markdown=previewCapabilitiesOf({extension:'md'}),pdf=previewCapabilitiesOf({extension:'pdf'}),video=previewCapabilitiesOf({extension:'mp4'});assert.equal(text.has('copy-content'),true);assert.equal(text.has('send-selection-to-chat'),true);assert.equal(markdown.has('copy-content'),true);assert.equal(pdf.has('copy-content'),false);assert.equal(pdf.has('screenshot'),false);assert.equal(video.has('screenshot'),true)})
test('merges workspace, WSL, then Everything results and removes duplicate paths',()=>{const merged=mergeSearchSources([[{path:'/work/a',source:'workspace'}],[{path:'/home/b',source:'wsl'},{path:'/work/a',source:'wsl'}],[{path:'/mnt/d/c',source:'everything'}]]);assert.deepEqual(merged.map(item=>item.source),['workspace','wsl','everything']);assert.deepEqual(merged.map(item=>item.path),['/work/a','/home/b','/mnt/d/c'])})
test('line preview follows DSH tokens without a visible path header',()=>{const html=renderDocument('/work/a.txt','hello');assert.match(html,/--dsw-alias-bg-layer-1/);assert.match(html,/--dsw-alias-label-primary/);assert.match(html,/--ds-font-family-code/);assert.doesNotMatch(html,/class="head"/);assert.doesNotMatch(html,/>\/work\/a\.txt<\/div>/)})
test('HTML and scripts render as inert source text',()=>{const html=renderDocument('/work/a.html','<script>alert(1)</script>');assert.match(html,/&lt;script&gt;alert\(1\)&lt;\/script&gt;/);assert.doesNotMatch(html,/<script>alert\(1\)<\/script>/)})
test('parses plus filters and filters only cached paths',()=>{assert.deepEqual(parseCachedSearchQuery('动画片 + 合集 + 1080p'),{base:'动画片',filters:['合集','1080p']});const items=[{name:'动画片合集.mkv',path:'/media/1080p/动画片合集.mkv'},{name:'动画片单集.mkv',path:'/media/720p/动画片单集.mkv'}];assert.deepEqual(filterCachedSearchItems(items,['合集','1080p']),[items[0]])})
test('routes suffixes to the required operation menus',()=>{assert.equal(previewMenuKind({extension:'ps1'}),'text');assert.equal(previewMenuKind({extension:'png'}),'image');assert.equal(previewMenuKind({extension:'mkv'}),'video');assert.equal(previewMenuKind({extension:'pdf',pdfKind:'image'}),'pdf-image');assert.equal(previewMenuKind({extension:'pdf',pdfKind:'mixed'}),'pdf-text');assert.equal(previewMenuKind({extension:'docx'}),'office');assert.equal(previewMenuKind({extension:'epub'}),'ebook');assert.equal(previewMenuKind({extension:'7z'}),'archive')})
