const inject = ['sessions','conversation']
const h = React.createElement
const CSS = `
.peekfile-btn{border:0;background:transparent;color:inherit;cursor:pointer;padding:6px 9px;border-radius:8px}.peekfile-btn:hover{background:var(--peek-hover)}.peekfile-btn:disabled{opacity:.4;cursor:not-allowed}
.peekfile-panel{--peek-bg:#fff;--peek-bg-soft:#f7f7f5;--peek-text:#37352f;--peek-muted:#787774;--peek-border:#e8e7e4;--peek-divider:rgba(55,53,47,.42);--peek-hover:#f1f1ef;--peek-accent:#2383e2;color-scheme:light;position:fixed;top:64px;right:24px;height:min(720px,calc(100vh - 88px));min-width:560px;min-height:360px;resize:both;z-index:3000;background:var(--peek-bg);color:var(--peek-text);border:1px solid var(--peek-border);border-radius:14px;box-shadow:0 18px 60px #0003;display:flex;flex-direction:column;overflow:hidden}.peekfile-panel.peekfile-browse{width:min(760px,calc(100vw - 48px))}.peekfile-panel.peekfile-previewing{width:min(1100px,calc(100vw - 48px))}
@media (prefers-color-scheme:dark){.peekfile-panel{--peek-bg:#191919;--peek-bg-soft:#242424;--peek-text:#e6e6e4;--peek-muted:#a3a3a0;--peek-border:#373737;--peek-divider:rgba(230,230,228,.42);--peek-hover:#2c2c2c;--peek-accent:#529cca;color-scheme:dark;box-shadow:0 18px 60px #0009}}
.peekfile-bar{display:flex;align-items:center;gap:8px;padding:12px 14px;border-bottom:1px solid var(--peek-border);cursor:move}.peekfile-searchbox{position:relative;flex:1}.peekfile-input{width:100%;box-sizing:border-box;background:var(--peek-bg-soft);color:inherit;border:1px solid var(--peek-border);border-radius:8px;padding:8px 11px;outline:none}.peekfile-input:focus{border-color:var(--peek-accent);box-shadow:0 0 0 2px color-mix(in srgb,var(--peek-accent) 20%,transparent)}.peekfile-history{position:absolute;top:calc(100% + 6px);left:0;right:0;z-index:5;padding:5px;background:var(--peek-bg);border:1px solid var(--peek-border);border-radius:9px;box-shadow:0 10px 30px #0003}.peekfile-history-item{display:flex;align-items:center;gap:8px;width:100%;padding:7px 9px;border:0;border-radius:6px;background:transparent;color:inherit;text-align:left;cursor:pointer}.peekfile-history-item:hover,.peekfile-history-item:focus{background:var(--peek-hover);outline:none}.peekfile-history-icon{color:var(--peek-muted)}.peekfile-history-text{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.peekfile-body{display:flex;min-height:0;flex:1}.peekfile-results{overflow:auto;flex:1;padding:0 12px 14px}.peekfile-listhead,.peekfile-row{display:grid;grid-template-columns:minmax(180px,1.25fr) 70px minmax(110px,.7fr) 72px 38px;gap:9px;align-items:center}.peekfile-listhead{padding:7px 22px;background:var(--peek-bg);color:var(--peek-muted);font-size:11px;border-bottom:1px solid var(--peek-border)}.peekfile-row{margin-top:3px;padding:8px 10px;border-left:2px solid var(--peek-file-color,#c99a6b);border-bottom:1px dashed var(--peek-divider);border-radius:0 6px 6px 0;cursor:pointer}.peekfile-row:hover,.peekfile-row.active{background:var(--peek-hover)}.peekfile-tone-folder{--peek-file-color:#d59a35}.peekfile-tone-document{--peek-file-color:#d97841}.peekfile-tone-sheet{--peek-file-color:#b89036}.peekfile-tone-slides{--peek-file-color:#e05a3f}.peekfile-tone-pdf{--peek-file-color:#c7473d}.peekfile-tone-image{--peek-file-color:#dc7b67}.peekfile-tone-media{--peek-file-color:#b96873}.peekfile-tone-book{--peek-file-color:#a96f45}.peekfile-tone-code{--peek-file-color:#c68457}.peekfile-tone-archive{--peek-file-color:#9f7658}.peekfile-tone-file{--peek-file-color:#c99a6b}.peekfile-name,.peekfile-path{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.peekfile-name{font-weight:500}.peekfile-type{color:var(--peek-muted);font-size:12px}.peekfile-path{font-size:11px;color:var(--peek-muted)}.peekfile-parent{color:var(--peek-accent);text-decoration:none}.peekfile-reason{justify-self:start;padding:2px 7px;border-radius:999px;background:color-mix(in srgb,var(--peek-file-color) 18%,transparent);color:var(--peek-text);font-size:10px;white-space:nowrap}.peekfile-footer{display:flex;align-items:center;gap:4px;min-height:40px;padding:4px 12px;background:var(--peek-bg);color:var(--peek-muted);font-size:11px;border-top:1px solid var(--peek-border)}.peekfile-footer-path{margin-left:6px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:var(--peek-text)}
.peekfile-preview{display:flex;flex:1;flex-direction:column;min-width:0;min-height:0}.peekfile-tabs{display:flex;overflow:auto;background:var(--peek-bg-soft);border-bottom:1px solid var(--peek-border)}.peekfile-tab{display:flex;gap:6px;align-items:center;padding:8px 10px;max-width:190px;cursor:pointer;border-right:1px solid var(--peek-border)}.peekfile-tab.active{background:var(--peek-bg)}.peekfile-tab-name{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.peekfile-tab-x{opacity:.6}.peekfile-frame{width:100%;height:100%;border:0;background:#fff}.peekfile-empty{display:grid;place-items:center;height:100%;color:var(--peek-muted)}
.peekfile-previewbar{display:flex;align-items:center;gap:5px;padding:6px 9px;border-bottom:1px solid var(--peek-border);font-size:11px}.peekfile-previewtitle{flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:var(--peek-muted)}
.peekfile-crumbs{display:flex;gap:3px;align-items:center;padding:7px 12px;overflow:auto;white-space:nowrap;border-bottom:1px solid var(--peek-border)}.peekfile-crumb{color:var(--peek-accent);cursor:pointer}.peekfile-error{padding:7px 12px;color:#e03e3e}.peekfile-link{color:var(--peek-accent);text-decoration:underline dotted;cursor:pointer}
.peekfile-settings{display:flex;flex-direction:column;gap:9px;padding:8px 0}.peekfile-setting{display:flex;align-items:center;justify-content:space-between;gap:16px}.peekfile-setting span{font-size:12px}.peekfile-setting select,.peekfile-setting input[type=number]{width:92px;background:transparent;color:inherit;border:1px solid rgba(127,127,127,.4);border-radius:6px;padding:3px 6px}
`
const api = async (method,args={}) => { const r=await fetch('/__peekfile/api',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({method,args})}); const j=await r.json(); if(!j.ok) throw new Error(j.error); return j.value }
const samePath = (a,b) => a?.path === b?.path
const linePreviewExtensions=new Set(['txt','log','json','js','mjs','cjs','jsx','ts','tsx','py','rs','go','java','c','cpp','h','hpp','css','scss','sh','zsh','yaml','yml','toml','ini','conf','xml','sql','vue','svelte'])
const isLinePreview=target=>linePreviewExtensions.has(String(target?.extension||'').toLowerCase())
const fileTone = item => {if(item.kind==='directory')return'folder';const extension=(item.extension||'').toLowerCase();if(['doc','docx','odt','rtf'].includes(extension))return'document';if(['xls','xlsx','ods','csv','tsv'].includes(extension))return'sheet';if(['ppt','pptx','odp'].includes(extension))return'slides';if(extension==='pdf')return'pdf';if(['png','jpg','jpeg','gif','webp','svg','bmp','ico','avif','heic'].includes(extension))return'image';if(['mp3','wav','flac','aac','m4a','ogg','mp4','mkv','mov','avi','webm','wmv'].includes(extension))return'media';if(['epub','mobi','azw','azw3','fb2'].includes(extension))return'book';if(['js','jsx','ts','tsx','py','go','rs','java','c','cc','cpp','h','hpp','cs','php','rb','sh','bash','zsh','ps1','html','css','scss','json','yaml','yml','toml','xml','md','txt'].includes(extension))return'code';if(['zip','rar','7z','tar','gz','bz2','xz'].includes(extension))return'archive';return'file'}

function apply(ctx){
  const slots=ctx.get('slots'); if(!slots)return
  ctx.effect(()=>{const style=document.createElement('style');style.textContent=CSS;document.head.appendChild(style);return()=>style.remove()})
  let openPanel=()=>{}
  const defaults={search:true,autoLink:true,codePaths:false,drops:true,limit:50,previewLimitMb:0,dropLimitMb:10}
  const loadSearchHistory=()=>{try{const values=JSON.parse(localStorage.getItem('peekfile:search-history')||'[]');return Array.isArray(values)?values.filter(value=>typeof value==='string'&&value.trim()).slice(0,10):[]}catch{return[]}}
  const updatedSearchHistory=(history,value)=>{const clean=String(value).trim();if(!clean)return history;const key=clean.toLocaleLowerCase();return[clean,...history.filter(item=>item.toLocaleLowerCase()!==key)].slice(0,10)}
  let preferences=defaults
  try{preferences={...defaults,...JSON.parse(localStorage.getItem('peekfile:settings')||'{}')}}catch{}
  const savePreferences=next=>{preferences={...preferences,...next};localStorage.setItem('peekfile:settings',JSON.stringify(preferences));window.dispatchEvent(new CustomEvent('peekfile:settings',{detail:preferences}))}
  const inputTriggers=ctx.get('inputTriggers')
  if(inputTriggers){try{ctx.effect(()=>inputTriggers.registerSource({trigger:'@',name:'file',order:30,candidates:async(_session,request)=>{if(!preferences.search||!request.query.trim())return[];try{const results=await api('search',{query:request.query,limit:10});return Promise.all(results.filter(item=>item.kind==='file').map(async item=>{const lineResult=await api('lines',{path:item.path}).catch(()=>({lines:1}));return{name:item.name,description:item.parent,hint:`${item.extension||'文件'} · ${lineResult.lines} 行`,peekfileTarget:item,peekfileLines:lineResult.lines}}))}catch{return[]}},onPick:({candidate})=>{const target=candidate.peekfileTarget;if(!target)return undefined;const lines=candidate.peekfileLines||1,token=`@${target.path}:1-${lines}`;return{insert:{source:'file',ref:token,label:`${target.name} 1-${lines}`,clipboardText:token}}},codec:{clipboardText:ref=>ref,serialize:ref=>Promise.resolve(ref)}}))}catch(error){console.warn('[peekfile] file reference codec:',error)}}
  const activeInput=()=>{const snapshot=ctx.sessions.list.getSnapshot(),sessionId=snapshot.current;if(!sessionId)return null;const actx=ctx.sessions.scope(sessionId);if(!actx)return null;return {sessionId,actx,shell:ctx.conversation.input.for(actx),cwd:snapshot.byId?.[sessionId]?.cwd||''}}
  const appendText=text=>{const current=activeInput();if(!current)return false;const draft=current.shell.state.getSnapshot().draft;current.shell.setDraft(draft.trim()===''?text:`${draft} ${text}`);return true}
  const insertReference=async(target,range=null)=>{if(target.kind==='directory')return appendText(`@${target.path.replace(/\/$/,'')}/ `);if(!isLinePreview(target))throw new Error('当前文件不是可按行引用的文本');const current=activeInput();if(!current)throw new Error('当前没有可用的对话输入框');const lineResult=range||await api('lines',{path:target.sourcePath||target.path}),start=range?.start||1,end=range?.end||lineResult.lines,path=target.sourcePath||target.path,token=`@${path}:${start}-${end}`,snapshot=current.shell.state.getSnapshot(),reference={source:'file',ref:token,label:target.name,clipboardText:token},inserted=current.actx.bail(current.actx,'slash/input-insert-reference',{reference,span:{start:snapshot.draft.length,end:snapshot.draft.length,draftRev:snapshot.draftRev}});if(inserted!==true)throw new Error('文件引用未能插入当前对话');return true}
  function Button(){return h('button',{className:'peekfile-btn',title:'PeekFile 文件搜索与预览',onClick:()=>openPanel()},'⌕ 文件')}
  function Panel(){
    const [open,setOpen]=React.useState(false),[view,setView]=React.useState('browse'),[query,setQuery]=React.useState(''),[history,setHistory]=React.useState(loadSearchHistory),[showHistory,setShowHistory]=React.useState(false),[items,setItems]=React.useState([]),[tabs,setTabs]=React.useState([]),[selected,setSelected]=React.useState(null),[error,setError]=React.useState(''),[cap,setCap]=React.useState(null),[directory,setDirectory]=React.useState(null),[lastSearch,setLastSearch]=React.useState(null),[position,setPosition]=React.useState(null),[reload,setReload]=React.useState(0),[prefs,setPrefs]=React.useState(preferences),[page,setPage]=React.useState(0),[hasMore,setHasMore]=React.useState(false)
    const frameRef=React.useRef(null)
    const openTarget=React.useCallback(async target=>{setOpen(true);if(!target){setView('browse');return}if(target.kind==='directory'){setView('browse');void browse(target.path);return}const previewLimit=Number(preferences.previewLimitMb)||0;if(previewLimit>0&&target.size>previewLimit*1024*1024){setError(`文件超过本地预览上限 ${previewLimit} MB`);return}try{if(['doc','docx','xls','xlsx','ppt','pptx','odt','ods','odp'].includes(target.extension)){setError('正在转换 Office 文档…');target={...await api('convert',{path:target.path}),name:target.name,sourcePath:target.path}}else if(['epub','mobi','azw','azw3'].includes(target.extension)){setError('正在准备电子书…');target={...await api('ebook',{path:target.path}),name:target.name,sourcePath:target.path}}setError('')}catch(e){setError(e.message);return}setTabs(old=>old.some(x=>samePath(x,target))?old:[...old,target]);setSelected(target);setView('previewing')},[])
    React.useEffect(()=>{openPanel=openTarget;return()=>{openPanel=()=>{}}},[openTarget])
    React.useEffect(()=>{if(open)api('capability').then(setCap).catch(e=>setError(e.message))},[open])
    React.useEffect(()=>{const listener=e=>setPrefs(e.detail);window.addEventListener('peekfile:settings',listener);return()=>window.removeEventListener('peekfile:settings',listener)},[])
    const search=async(nextPage=0,nextQuery=query)=>{const searchQuery=String(nextQuery).trim();if(!searchQuery)return;try{setError('');setShowHistory(false);setDirectory(null);setQuery(searchQuery);const result=await api('search-page',{query:searchQuery,page:nextPage,pageSize:prefs.limit}),snapshot={query:searchQuery,items:result.items,page:result.page,hasMore:result.hasMore};setItems(snapshot.items);setPage(snapshot.page);setHasMore(snapshot.hasMore);setLastSearch(snapshot);if(nextPage===0)setHistory(old=>{const next=updatedSearchHistory(old,searchQuery);localStorage.setItem('peekfile:search-history',JSON.stringify(next));return next})}catch(e){setError(e.message)}}
    const browse=async path=>{try{setError('');const result=await api('list',{path});setDirectory(result);setItems(result.items)}catch(e){setError(e.message)}}
    const backToSearch=()=>{if(!lastSearch)return;setError('');setDirectory(null);setQuery(lastSearch.query);setItems(lastSearch.items);setPage(lastSearch.page);setHasMore(lastSearch.hasMore)}
    const activate=item=>item.kind==='directory'?browse(item.path):openTarget(item)
    const closeTab=(item,event)=>{event?.stopPropagation();setTabs(old=>{const next=old.filter(x=>!samePath(x,item));if(samePath(selected,item)){const fallback=next.at(-1)||null;setSelected(fallback);if(!fallback)setView('browse')}return next})}
    const download=async()=>{if(!selected)return;try{const source=selected.sourcePath?await api('resolve',{candidates:[selected.sourcePath]}):null,target=source?.items?.find(x=>x.ok)?.target||selected;const anchor=document.createElement('a');anchor.href=target.previewUrl;anchor.download=selected.name;anchor.click()}catch(e){setError(e.message)}}
    const detach=async()=>{if(!selected)return;try{if(window.documentPictureInPicture?.requestWindow){const pip=await window.documentPictureInPicture.requestWindow({width:900,height:650}),frame=pip.document.createElement('iframe');frame.src=selected.previewUrl;frame.title=selected.name;Object.assign(frame.style,{position:'fixed',inset:'0',width:'100%',height:'100%',border:'0',background:'#fff'});pip.document.body.style.margin='0';pip.document.body.appendChild(frame);return}const popup=window.open(selected.previewUrl,'peekfile-preview','popup,width=1000,height=720,resizable=yes,scrollbars=yes');if(popup)return;setError('浏览器阻止了弹窗，已继续使用页面内浮窗')}catch{const popup=window.open(selected.previewUrl,'peekfile-preview','popup,width=1000,height=720,resizable=yes,scrollbars=yes');if(!popup)setError('PiP 与 Popup 均不可用，已继续使用页面内浮窗')}}
    const openSystem=async()=>{if(!selected)return;try{await api('open-system',{path:selected.sourcePath||selected.path})}catch(e){setError(e.message)}}
    const addWhole=async()=>{try{await insertReference(selected);setError('')}catch(e){setError(e.message)}}
    const addSelection=async()=>{try{const selection=frameRef.current?.contentDocument?.getSelection();if(!selection||selection.isCollapsed)throw new Error('请先在代码或文本预览中选择内容');const lineOf=node=>{const element=node?.nodeType===1?node:node?.parentElement;const line=element?.closest?.('.line')?.id||'';return Number(line.replace(/^L/,''))||null},a=lineOf(selection.anchorNode),b=lineOf(selection.focusNode);if(!a||!b)throw new Error('当前预览不支持选区行号');await insertReference(selected,{start:Math.min(a,b),end:Math.max(a,b)});setError('')}catch(e){setError(e.message)}}
    const dragStart=e=>{if(e.target.closest('input,button'))return;const panel=e.currentTarget.parentElement;const rect=panel.getBoundingClientRect(),sx=e.clientX,sy=e.clientY;const move=ev=>setPosition({left:rect.left+ev.clientX-sx,top:rect.top+ev.clientY-sy});const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up)};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)}
    if(!open)return null
    return h('div',{className:`peekfile-panel peekfile-${view}`,style:position?{left:Math.max(0,position.left),top:Math.max(0,position.top),right:'auto'}:undefined},
      view==='browse'?h(React.Fragment,null,h('div',{className:'peekfile-bar',onPointerDown:dragStart},h('div',{className:'peekfile-searchbox'},h('input',{className:'peekfile-input',value:query,placeholder:cap?.everything===false?'EverythingCLI 未安装：对话路径预览仍可用':'搜索本地文件',disabled:cap?.everything===false||!prefs.search,onFocus:()=>setShowHistory(true),onBlur:()=>setTimeout(()=>setShowHistory(false),120),onChange:e=>{setQuery(e.target.value);setShowHistory(true)},onKeyDown:e=>{if(e.key==='Enter')void search()}}),showHistory&&history.length?h('div',{className:'peekfile-history'},history.map(value=>h('button',{className:'peekfile-history-item',key:value,onPointerDown:e=>e.preventDefault(),onClick:()=>void search(0,value)},h('span',{className:'peekfile-history-icon'},'↺'),h('span',{className:'peekfile-history-text'},value)))):null),h('button',{className:'peekfile-btn',onClick:()=>search(),disabled:cap?.everything===false||!prefs.search},'搜索'),directory&&lastSearch?h('button',{className:'peekfile-btn',onClick:backToSearch,title:'返回本次搜索列表'},'返回'):null,h('button',{className:'peekfile-btn',onClick:()=>setOpen(false)},'关闭')),items.length?h('div',{className:'peekfile-listhead'},h('span',null,'名称'),h('span',null,'类型'),h('span',null,'上级目录'),h('span',null,'命中原因'),h('span',null,'')):null):null,
      error?h('div',{className:'peekfile-error'},error):null,
      h('div',{className:'peekfile-body'},
        view==='browse'?h('div',{className:'peekfile-results'},items.length?items.map(item=>h('div',{className:`peekfile-row peekfile-tone-${fileTone(item)}${samePath(selected,item)?' active':''}`,key:item.path,onClick:()=>activate(item)},h('span',{className:'peekfile-name'},item.kind==='directory'?'📁 ':'📄 ',item.name),h('span',{className:'peekfile-type'},item.extension||'文件夹'),h('span',{className:`peekfile-path${!directory?' peekfile-parent':''}`,title:item.parent,onClick:!directory?e=>{e.stopPropagation();browse(item.parent)}:undefined},item.parent),item.reason&&!directory?h('span',{className:'peekfile-reason',title:`Everything 命中：${item.reason}`},item.reason):h('span',null,''),h('button',{className:'peekfile-btn',title:'添加到对话',onClick:e=>{e.stopPropagation();void insertReference(item)}},'@'))):h('div',{className:'peekfile-empty'},query?'没有找到匹配文件':'输入关键词开始搜索')):null,
        view==='previewing'?h('div',{className:'peekfile-preview'},h('div',{className:'peekfile-tabs'},tabs.map(tab=>h('div',{className:`peekfile-tab${samePath(selected,tab)?' active':''}`,key:tab.path,onClick:()=>{setSelected(tab);setView('previewing')},onAuxClick:e=>e.button===1&&closeTab(tab,e)},h('span',{className:'peekfile-tab-name',title:tab.path},tab.name),h('span',{className:'peekfile-tab-x',onClick:e=>closeTab(tab,e)},'×')))),selected?h(React.Fragment,null,h('div',{className:'peekfile-previewbar'},h('button',{className:'peekfile-btn',onClick:()=>setView('browse')},'← 文件列表'),h('span',{className:'peekfile-previewtitle',title:selected.sourcePath||selected.path},selected.sourcePath||selected.path),isLinePreview(selected)?h(React.Fragment,null,h('button',{className:'peekfile-btn',onClick:addWhole},'全文到对话'),h('button',{className:'peekfile-btn',onClick:addSelection},'选区到对话')):null,h('button',{className:'peekfile-btn',onClick:detach},'弹出'),h('button',{className:'peekfile-btn',onClick:openSystem},'系统打开'),h('button',{className:'peekfile-btn',onClick:()=>setReload(x=>x+1)},'刷新'),h('button',{className:'peekfile-btn',onClick:download},'下载'),h('button',{className:'peekfile-btn',onClick:()=>setOpen(false)},'关闭')),h('iframe',{ref:frameRef,key:reload,className:'peekfile-frame',src:selected.previewUrl,title:selected.name})):h('div',{className:'peekfile-empty'},'选择文件进行预览')):null)
      ,view==='browse'?h('div',{className:'peekfile-footer'},cap?.everything===false?'预览模式：EverythingCLI 不可用':h(React.Fragment,null,`第 ${page+1} 页 · ${directory?items.length:lastSearch?.items.length||items.length} 项`,h('button',{className:'peekfile-btn',disabled:!!directory||page===0,onClick:()=>search(page-1)},'上一页'),h('button',{className:'peekfile-btn',disabled:!!directory||!hasMore,onClick:()=>search(page+1)},'下一页')),directory?h(React.Fragment,null,h('button',{className:'peekfile-btn',onClick:()=>browse(directory.parent),title:'上级目录'},'↑'),h('span',{className:'peekfile-footer-path',title:directory.path},directory.path)):null):null
    )
  }
  slots.inject('conversation.session.header.utilities',()=>slots.register({name:'conversation.session.header.utilities',id:'peekfile-button',label:'PeekFile',order:9},Button))
  slots.inject('shell.overlay',()=>slots.register({name:'shell.overlay',id:'peekfile-panel',order:9},Panel))
  function SettingsCard(){const [value,setValue]=React.useState(preferences),change=(key,next)=>{const merged={...value,[key]:next};setValue(merged);savePreferences(merged)};return h('div',{className:'peekfile-settings'},h('strong',null,'PeekFile'),[['search','启用 Everything 搜索'],['autoLink','自动链接对话本地路径'],['codePaths','识别代码块中的路径'],['drops','允许拖入非图片文件']].map(([key,label])=>h('label',{className:'peekfile-setting',key},h('span',null,label),h('input',{type:'checkbox',checked:value[key],onChange:e=>change(key,e.target.checked)}))),h('label',{className:'peekfile-setting'},h('span',null,'搜索结果上限'),h('select',{value:value.limit,onChange:e=>change('limit',Number(e.target.value))},[10,25,50,100].map(n=>h('option',{key:n,value:n},n)))),h('label',{className:'peekfile-setting'},h('span',null,'本地预览上限（MB，0 为不限制）'),h('input',{type:'number',min:0,step:1,value:value.previewLimitMb,onChange:e=>change('previewLimitMb',Math.max(0,Number(e.target.value)||0))})),h('label',{className:'peekfile-setting'},h('span',null,'拖入对话框上限（MB）'),h('input',{type:'number',min:1,step:1,value:value.dropLimitMb,onChange:e=>change('dropLimitMb',Math.max(1,Number(e.target.value)||10))}))) }
  slots.inject('web-ui.plugin.item',()=>slots.register({name:'web-ui.plugin.item',id:'peekfile-settings',label:'PeekFile',order:120},SettingsCard))
  ctx.effect(()=>{
    const re=/(?<![\w@.])(?:[A-Za-z]:[\\/][^\n<>"'`]+?|(?:\/home\/|\/mnt\/|~\/)[^\n<>"'`]+?\.[A-Za-z0-9]{1,12})(?=[\s),;]|$)/g
    const process=async root=>{if(!preferences.autoLink||!root?.isConnected)return;const nodes=[],walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let node;while((node=walker.nextNode())){const excluded=preferences.codePaths?'.peekfile-panel,a,input,textarea,[contenteditable=true]':'.peekfile-panel,a,pre,code,input,textarea,[contenteditable=true]';if(node.parentElement?.closest(excluded))continue;const matches=node.nodeValue?.match(re);if(matches)nodes.push([node,[...new Set(matches)]])}for(const [textNode,candidates] of nodes){const result=await api('resolve',{candidates}).catch(()=>null);if(!result)continue;const hit=result.items.find(x=>x.ok);if(!hit||!textNode.isConnected||!textNode.nodeValue.includes(hit.candidate))continue;const parts=textNode.nodeValue.split(hit.candidate),fragment=document.createDocumentFragment();parts.forEach((part,i)=>{fragment.append(part);if(i<parts.length-1){const link=document.createElement('a');link.className='peekfile-link';link.textContent=hit.candidate;link.href=hit.target.previewUrl;link.onclick=e=>{e.preventDefault();openPanel(hit.target)};fragment.append(link)}});textNode.replaceWith(fragment)}}
    const observer=new MutationObserver(records=>records.forEach(record=>record.addedNodes.forEach(node=>node.nodeType===1&&process(node))));observer.observe(document.body,{childList:true,subtree:true});void process(document.body);return()=>observer.disconnect()
  })
  ctx.effect(()=>{
    const onDragOver=event=>{if(!preferences.drops)return;const files=[...(event.dataTransfer?.files||[])];if(files.some(file=>!file.type.startsWith('image/')))event.preventDefault()}
    const onDrop=async event=>{if(!preferences.drops)return;const files=[...(event.dataTransfer?.files||[])];if(!files.some(file=>!file.type.startsWith('image/')))return;event.preventDefault();const current=activeInput();if(!current?.cwd)return;const dropLimit=Math.max(1,Number(preferences.dropLimitMb)||10);for(const file of files){if(file.size>dropLimit*1024*1024){console.warn(`[peekfile] ${file.name} 超过拖入上限 ${dropLimit} MB`);continue}try{const response=await fetch('/__peekfile/upload',{method:'POST',headers:{'x-peekfile-root':encodeURIComponent(current.cwd),'x-peekfile-name':encodeURIComponent(file.name),'x-peekfile-limit-mb':String(dropLimit),'content-type':file.type||'application/octet-stream'},body:file}),result=await response.json();if(result.ok)await insertReference(result.value)}catch(error){console.warn('[peekfile] drop upload failed',error)}}}
    document.addEventListener('dragover',onDragOver);document.addEventListener('drop',onDrop);return()=>{document.removeEventListener('dragover',onDragOver);document.removeEventListener('drop',onDrop)}
  })
}
