const inject = []
const h = React.createElement
const CSS = `
.peekfile-btn{border:0;background:transparent;color:inherit;cursor:pointer;padding:6px 9px;border-radius:8px}.peekfile-btn:hover{background:rgba(127,127,127,.16)}.peekfile-btn:disabled{opacity:.4;cursor:not-allowed}
.peekfile-panel{position:fixed;top:64px;right:24px;width:min(980px,calc(100vw - 48px));height:min(720px,calc(100vh - 88px));min-width:560px;min-height:360px;resize:both;z-index:3000;background:var(--dsw-alias-bg-overlay,#171a21);color:var(--dsw-alias-label-primary,#eee);border:1px solid rgba(127,127,127,.35);border-radius:14px;box-shadow:0 18px 60px #0008;display:flex;flex-direction:column;overflow:hidden}
.peekfile-bar{display:flex;align-items:center;gap:8px;padding:10px;border-bottom:1px solid rgba(127,127,127,.25);cursor:move}.peekfile-input{flex:1;background:transparent;color:inherit;border:1px solid rgba(127,127,127,.4);border-radius:8px;padding:7px 10px}.peekfile-status{padding:6px 10px;font-size:11px;opacity:.75;border-bottom:1px solid rgba(127,127,127,.18)}
.peekfile-body{display:grid;grid-template-columns:minmax(320px,42%) 1fr;min-height:0;flex:1}.peekfile-results{overflow:auto;border-right:1px solid rgba(127,127,127,.25)}.peekfile-row{display:grid;grid-template-columns:minmax(0,1fr) 70px;padding:8px 10px;border-bottom:1px solid rgba(127,127,127,.15);cursor:pointer}.peekfile-row:hover,.peekfile-row.active{background:rgba(79,140,255,.14)}.peekfile-name{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.peekfile-path{font-size:10px;opacity:.65;grid-column:1/-1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.peekfile-parent{color:#64a0ff;text-decoration:underline dotted}
.peekfile-preview{display:flex;flex-direction:column;min-width:0;min-height:0}.peekfile-tabs{display:flex;overflow:auto;border-bottom:1px solid rgba(127,127,127,.25)}.peekfile-tab{display:flex;gap:6px;align-items:center;padding:7px 9px;max-width:180px;cursor:pointer;border-right:1px solid rgba(127,127,127,.2)}.peekfile-tab.active{background:rgba(79,140,255,.16)}.peekfile-tab-name{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.peekfile-tab-x{opacity:.6}.peekfile-frame{width:100%;height:100%;border:0;background:#fff}.peekfile-empty{display:grid;place-items:center;height:100%;opacity:.65}
.peekfile-previewbar{display:flex;align-items:center;gap:5px;padding:4px 7px;border-bottom:1px solid rgba(127,127,127,.18);font-size:11px}.peekfile-previewtitle{flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;opacity:.7}
.peekfile-crumbs{display:flex;gap:3px;align-items:center;padding:7px 10px;overflow:auto;white-space:nowrap;border-bottom:1px solid rgba(127,127,127,.18)}.peekfile-crumb{color:#64a0ff;cursor:pointer}.peekfile-error{padding:7px 10px;color:#ff7777}.peekfile-link{color:#4f8cff;text-decoration:underline dotted;cursor:pointer}
`
const api = async (method,args={}) => { const r=await fetch('/__peekfile/api',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({method,args})}); const j=await r.json(); if(!j.ok) throw new Error(j.error); return j.value }
const samePath = (a,b) => a?.path === b?.path

function apply(ctx){
  const slots=ctx.get('slots'); if(!slots)return
  ctx.effect(()=>{const style=document.createElement('style');style.textContent=CSS;document.head.appendChild(style);return()=>style.remove()})
  let openPanel=()=>{}
  function Button(){return h('button',{className:'peekfile-btn',title:'PeekFile 文件搜索与预览',onClick:()=>openPanel()},'⌕ 文件')}
  function Panel(){
    const [open,setOpen]=React.useState(false),[query,setQuery]=React.useState(''),[items,setItems]=React.useState([]),[tabs,setTabs]=React.useState([]),[selected,setSelected]=React.useState(null),[error,setError]=React.useState(''),[cap,setCap]=React.useState(null),[directory,setDirectory]=React.useState(null),[position,setPosition]=React.useState(null),[reload,setReload]=React.useState(0)
    const openTarget=React.useCallback(async target=>{setOpen(true);if(!target)return;if(target.kind==='directory'){void browse(target.path);return}try{if(['doc','docx','xls','xlsx','ppt','pptx','odt','ods','odp'].includes(target.extension)){setError('正在转换 Office 文档…');target={...await api('convert',{path:target.path}),name:target.name,sourcePath:target.path}}else if(['epub','mobi','azw','azw3'].includes(target.extension)){setError('正在准备电子书…');target={...await api('ebook',{path:target.path}),name:target.name,sourcePath:target.path}}setError('')}catch(e){setError(e.message);return}setTabs(old=>old.some(x=>samePath(x,target))?old:[...old,target]);setSelected(target)},[])
    React.useEffect(()=>{openPanel=openTarget;return()=>{openPanel=()=>{}}},[openTarget])
    React.useEffect(()=>{if(open)api('capability').then(setCap).catch(e=>setError(e.message))},[open])
    const search=async()=>{try{setError('');setDirectory(null);setItems(await api('search',{query,limit:50}))}catch(e){setError(e.message)}}
    const browse=async path=>{try{setError('');const result=await api('list',{path});setDirectory(result);setItems(result.items)}catch(e){setError(e.message)}}
    const activate=item=>item.kind==='directory'?browse(item.path):openTarget(item)
    const closeTab=(item,event)=>{event?.stopPropagation();setTabs(old=>{const next=old.filter(x=>!samePath(x,item));if(samePath(selected,item))setSelected(next.at(-1)||null);return next})}
    const download=async()=>{if(!selected)return;try{const source=selected.sourcePath?await api('resolve',{candidates:[selected.sourcePath]}):null,target=source?.items?.find(x=>x.ok)?.target||selected;const anchor=document.createElement('a');anchor.href=target.previewUrl;anchor.download=selected.name;anchor.click()}catch(e){setError(e.message)}}
    const relativeDir=directory?.path?.slice(directory.root.length).replace(/^\//,'')||'',crumbs=relativeDir?relativeDir.split('/'):[]
    const dragStart=e=>{if(e.target.closest('input,button'))return;const panel=e.currentTarget.parentElement;const rect=panel.getBoundingClientRect(),sx=e.clientX,sy=e.clientY;const move=ev=>setPosition({left:rect.left+ev.clientX-sx,top:rect.top+ev.clientY-sy});const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up)};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)}
    if(!open)return null
    return h('div',{className:'peekfile-panel',style:position?{left:Math.max(0,position.left),top:Math.max(0,position.top),right:'auto'}:undefined},
      h('div',{className:'peekfile-bar',onPointerDown:dragStart},h('input',{className:'peekfile-input',value:query,placeholder:cap?.everything===false?'EverythingCLI 未安装：对话路径预览仍可用':'搜索本地文件',disabled:cap?.everything===false,onChange:e=>setQuery(e.target.value),onKeyDown:e=>e.key==='Enter'&&search()}),h('button',{className:'peekfile-btn',onClick:search,disabled:cap?.everything===false},'搜索'),h('button',{className:'peekfile-btn',onClick:()=>setOpen(false)},'关闭')),
      directory?h('div',{className:'peekfile-crumbs'},h('button',{className:'peekfile-btn',onClick:()=>browse(directory.parent)},'↑'),h('span',{className:'peekfile-crumb',onClick:()=>browse(directory.root)},directory.root),crumbs.map((part,i)=>h(React.Fragment,{key:i},h('span',null,'›'),h('span',{className:'peekfile-crumb',onClick:()=>browse(directory.root+'/'+crumbs.slice(0,i+1).join('/'))},part)))):h('div',{className:'peekfile-status'},cap?.everything===false?'预览模式：EverythingCLI 不可用':`${items.length} 个结果`),
      error?h('div',{className:'peekfile-error'},error):null,
      h('div',{className:'peekfile-body'},
        h('div',{className:'peekfile-results'},items.map(item=>h('div',{className:`peekfile-row${samePath(selected,item)?' active':''}`,key:item.path,onClick:()=>activate(item)},h('span',{className:'peekfile-name'},item.kind==='directory'?'📁 ':'📄 ',item.name),h('span',null,item.extension||'目录'),h('span',{className:`peekfile-path${!directory?' peekfile-parent':''}`,title:item.parent,onClick:!directory?e=>{e.stopPropagation();browse(item.parent)}:undefined},directory?item.path:item.parent+(item.reason?' · '+item.reason:''))))),
        h('div',{className:'peekfile-preview'},h('div',{className:'peekfile-tabs'},tabs.map(tab=>h('div',{className:`peekfile-tab${samePath(selected,tab)?' active':''}`,key:tab.path,onClick:()=>setSelected(tab),onAuxClick:e=>e.button===1&&closeTab(tab,e)},h('span',{className:'peekfile-tab-name',title:tab.path},tab.name),h('span',{className:'peekfile-tab-x',onClick:e=>closeTab(tab,e)},'×')))),selected?h(React.Fragment,null,h('div',{className:'peekfile-previewbar'},h('span',{className:'peekfile-previewtitle',title:selected.sourcePath||selected.path},selected.sourcePath||selected.path),h('button',{className:'peekfile-btn',onClick:()=>setReload(x=>x+1)},'刷新'),h('button',{className:'peekfile-btn',onClick:download},'下载')),h('iframe',{key:reload,className:'peekfile-frame',src:selected.previewUrl,title:selected.name})):h('div',{className:'peekfile-empty'},'选择文件进行预览')))
    )
  }
  slots.inject('conversation.session.header.utilities',()=>slots.register({name:'conversation.session.header.utilities',id:'peekfile-button',label:'PeekFile',order:9},Button))
  slots.inject('shell.overlay',()=>slots.register({name:'shell.overlay',id:'peekfile-panel',order:9},Panel))
  ctx.effect(()=>{
    const re=/(?<![\w@.])(?:[A-Za-z]:[\\/][^\n<>"'`]+?|(?:\/home\/|\/mnt\/|~\/)[^\n<>"'`]+?\.[A-Za-z0-9]{1,12})(?=[\s),;]|$)/g
    const process=async root=>{if(!root?.isConnected)return;const nodes=[],walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let node;while((node=walker.nextNode())){if(node.parentElement?.closest('.peekfile-panel,a,pre,code,input,textarea,[contenteditable=true]'))continue;const matches=node.nodeValue?.match(re);if(matches)nodes.push([node,[...new Set(matches)]])}for(const [textNode,candidates] of nodes){const result=await api('resolve',{candidates}).catch(()=>null);if(!result)continue;const hit=result.items.find(x=>x.ok);if(!hit||!textNode.isConnected||!textNode.nodeValue.includes(hit.candidate))continue;const parts=textNode.nodeValue.split(hit.candidate),fragment=document.createDocumentFragment();parts.forEach((part,i)=>{fragment.append(part);if(i<parts.length-1){const link=document.createElement('a');link.className='peekfile-link';link.textContent=hit.candidate;link.href=hit.target.previewUrl;link.onclick=e=>{e.preventDefault();openPanel(hit.target)};fragment.append(link)}});textNode.replaceWith(fragment)}}
    const observer=new MutationObserver(records=>records.forEach(record=>record.addedNodes.forEach(node=>node.nodeType===1&&process(node))));observer.observe(document.body,{childList:true,subtree:true});void process(document.body);return()=>observer.disconnect()
  })
}
