import { extname } from 'node:path'

const esc=value=>String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')
const themeBridge=`<script>(()=>{const apply=()=>{try{if(parent===window)return;const source=parent.getComputedStyle(parent.document.body),root=document.documentElement,map={'--pf-bg':'--dsw-alias-bg-layer-1','--pf-layer':'--dsw-alias-bg-layer-2','--pf-text':'--dsw-alias-label-primary','--pf-muted':'--dsw-alias-label-tertiary','--pf-border':'--dsw-alias-border-l2','--pf-hover':'--dsw-alias-interactive-bg-hover','--pf-active':'--dsw-alias-interactive-bg-active','--pf-accent':'--dsw-alias-state-business-primary','--pf-code-font':'--ds-font-family-code'};for(const [target,token] of Object.entries(map)){const value=source.getPropertyValue(token).trim();if(value)root.style.setProperty(target,value)}const dark=parent.document.body.hasAttribute('data-ds-dark-theme');root.toggleAttribute('data-dark',dark);root.style.colorScheme=dark?'dark':'light'}catch{}};apply();try{if(parent!==window)new MutationObserver(apply).observe(parent.document.body,{attributes:true,attributeFilter:['data-ds-dark-theme','style','class']})}catch{}})()</script>`
const shell=(title,body,script='')=>`<!doctype html><html><head><meta charset="utf-8"><title>${esc(title)}</title><style>:root{color-scheme:light;--pf-bg:#fff;--pf-layer:#f7f7f5;--pf-text:#37352f;--pf-muted:#787774;--pf-border:#e8e7e4;--pf-hover:rgba(38,49,72,.06);--pf-active:rgba(38,49,72,.1);--pf-accent:#4176e6;--pf-code-font:ui-monospace,SFMono-Regular,Consolas,monospace}:root[data-dark]{color-scheme:dark;--pf-bg:#232324;--pf-layer:#29292b;--pf-text:#f2f2f3;--pf-muted:#96969c;--pf-border:rgba(255,255,255,.12);--pf-hover:rgba(255,255,255,.08);--pf-active:rgba(255,255,255,.14);--pf-accent:#679efe}html,body{min-height:100%;background:var(--pf-bg);color:var(--pf-text)}body{margin:0;font:14px/1.65 system-ui,sans-serif}.content{padding:14px 18px}pre{margin:0;font:13px/1.65 var(--pf-code-font);white-space:pre;overflow:auto}.line{display:block}.line:hover{background:var(--pf-hover)}.line:target,.line.focus{background:var(--pf-active)}.ln{display:inline-block;width:48px;margin-right:12px;text-align:right;color:var(--pf-muted);user-select:none}table{border-collapse:collapse;width:100%;font-size:12px}th,td{border:1px solid var(--pf-border);padding:5px 8px;text-align:left}th{position:sticky;top:0;background:var(--pf-layer)}h1,h2,h3{line-height:1.25}a{color:var(--pf-accent)}code{background:var(--pf-layer);padding:1px 5px;border-radius:4px}blockquote{border-left:3px solid var(--pf-border);padding-left:12px;color:var(--pf-muted)}</style>${themeBridge}</head><body><div class="content">${body}</div>${script}</body></html>`
const codePage=(title,text,start,end)=>{const lines=text.split('\n'),body=lines.map((line,index)=>{const n=index+1,focus=n>=start&&n<=end?' focus':'';return`<span id="L${n}" class="line${focus}"><span class="ln">${n}</span>${esc(line)}</span>`}).join('');return shell(title,`<pre>${body}</pre>`,`<script>const e=document.getElementById('L${Number(start)||1}');if(e)e.scrollIntoView({block:'center'})</script>`)}
const markdownPage=(title,text)=>{let code=false;const out=[];for(const raw of text.split('\n')){if(/^```/.test(raw.trim())){out.push(code?'</code></pre>':'<pre><code>');code=!code;continue}if(code){out.push(esc(raw)+'\n');continue}const line=raw.trim();if(/^### /.test(line))out.push(`<h3>${esc(line.slice(4))}</h3>`);else if(/^## /.test(line))out.push(`<h2>${esc(line.slice(3))}</h2>`);else if(/^# /.test(line))out.push(`<h1>${esc(line.slice(2))}</h1>`);else if(/^> ?/.test(line))out.push(`<blockquote>${esc(line.replace(/^> ?/,''))}</blockquote>`);else if(/^[-*] /.test(line))out.push(`<li>${esc(line.slice(2))}</li>`);else if(line)out.push(`<p>${esc(line).replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>')}</p>`)}if(code)out.push('</code></pre>');return shell(title,out.join('\n'))}
const csvPage=(title,text)=>{const rows=text.split(/\r?\n/).filter(Boolean).map(line=>line.split(',')),body=rows.map((row,index)=>`<tr>${row.map(cell=>index===0?`<th>${esc(cell)}</th>`:`<td>${esc(cell)}</td>`).join('')}</tr>`).join('');return shell(title,`<table>${body}</table>`)}
const lineExtensions=['.txt','.log','.md','.markdown','.rst','.adoc','.org','.tex','.json','.jsonl','.js','.mjs','.cjs','.jsx','.ts','.tsx','.py','.rs','.go','.java','.c','.cc','.cpp','.h','.hpp','.cs','.php','.rb','.pl','.pm','.lua','.swift','.kt','.kts','.scala','.r','.dart','.ex','.exs','.erl','.hrl','.clj','.cljs','.groovy','.gradle','.asm','.s','.sol','.proto','.graphql','.gql','.sh','.bash','.zsh','.fish','.ps1','.bat','.cmd','.css','.scss','.less','.yaml','.yml','.toml','.ini','.cfg','.conf','.properties','.env','.lock','.xml','.sql','.vue','.svelte','.html','.htm','.xhtml','.csv','.tsv','.srt','.vtt','.ass','.ssa','.sub']
export const lineRenderable=path=>lineExtensions.includes(extname(path).toLowerCase())
export const renderable=path=>lineRenderable(path)||['.md','.markdown','.csv'].includes(extname(path).toLowerCase())
export const renderDocument=(path,text,{lineStart=1,lineEnd=lineStart}={})=>{const ext=extname(path).toLowerCase();if(ext==='.md'||ext==='.markdown')return markdownPage(path,text);return codePage(path,text,lineStart,lineEnd)}
