import { extname } from 'node:path'

const esc=value=>String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')
const shell=(title,body,script='')=>`<!doctype html><html><head><meta charset="utf-8"><title>${esc(title)}</title><style>body{margin:0;background:#0d1117;color:#e6edf3;font:14px/1.65 system-ui,sans-serif}.head{position:sticky;top:0;padding:8px 14px;background:#161b22;border-bottom:1px solid #30363d;color:#8b949e}.content{padding:14px 18px}pre{margin:0;font:12px/1.65 ui-monospace,monospace;white-space:pre;overflow:auto}.line{display:block}.line:target,.line.focus{background:#23395d}.ln{display:inline-block;width:48px;margin-right:12px;text-align:right;color:#59636e;user-select:none}table{border-collapse:collapse;width:100%;font-size:12px}th,td{border:1px solid #30363d;padding:5px 8px;text-align:left}th{position:sticky;top:37px;background:#21262d}h1,h2,h3{line-height:1.25}a{color:#58a6ff}code{background:#21262d;padding:1px 5px;border-radius:4px}blockquote{border-left:3px solid #59636e;padding-left:12px;color:#9da7b3}</style></head><body><div class="head">${esc(title)}</div><div class="content">${body}</div>${script}</body></html>`
const codePage=(title,text,start,end)=>{const lines=text.split('\n'),body=lines.map((line,index)=>{const n=index+1,focus=n>=start&&n<=end?' focus':'';return`<span id="L${n}" class="line${focus}"><span class="ln">${n}</span>${esc(line)}</span>`}).join('');return shell(title,`<pre>${body}</pre>`,`<script>const e=document.getElementById('L${Number(start)||1}');if(e)e.scrollIntoView({block:'center'})</script>`)}
const markdownPage=(title,text)=>{let code=false;const out=[];for(const raw of text.split('\n')){if(/^```/.test(raw.trim())){out.push(code?'</code></pre>':'<pre><code>');code=!code;continue}if(code){out.push(esc(raw)+'\n');continue}const line=raw.trim();if(/^### /.test(line))out.push(`<h3>${esc(line.slice(4))}</h3>`);else if(/^## /.test(line))out.push(`<h2>${esc(line.slice(3))}</h2>`);else if(/^# /.test(line))out.push(`<h1>${esc(line.slice(2))}</h1>`);else if(/^> ?/.test(line))out.push(`<blockquote>${esc(line.replace(/^> ?/,''))}</blockquote>`);else if(/^[-*] /.test(line))out.push(`<li>${esc(line.slice(2))}</li>`);else if(line)out.push(`<p>${esc(line).replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>')}</p>`)}if(code)out.push('</code></pre>');return shell(title,out.join('\n'))}
const csvPage=(title,text)=>{const rows=text.split(/\r?\n/).filter(Boolean).map(line=>line.split(',')),body=rows.map((row,index)=>`<tr>${row.map(cell=>index===0?`<th>${esc(cell)}</th>`:`<td>${esc(cell)}</td>`).join('')}</tr>`).join('');return shell(title,`<table>${body}</table>`)}
const lineExtensions=['.txt','.log','.json','.js','.mjs','.cjs','.jsx','.ts','.tsx','.py','.rs','.go','.java','.c','.cpp','.h','.hpp','.css','.scss','.sh','.zsh','.yaml','.yml','.toml','.ini','.conf','.xml','.sql','.vue','.svelte']
export const lineRenderable=path=>lineExtensions.includes(extname(path).toLowerCase())
export const renderable=path=>lineRenderable(path)||['.md','.markdown','.csv'].includes(extname(path).toLowerCase())
export const renderDocument=(path,text,{lineStart=1,lineEnd=lineStart}={})=>{const ext=extname(path).toLowerCase();if(ext==='.md'||ext==='.markdown')return markdownPage(path,text);if(ext==='.csv')return csvPage(path,text);return codePage(path,text,lineStart,lineEnd)}
